CREATE TABLE [dbo].[TBL_USER]
(
    [NAME] NVARCHAR(30) NOT NULL PRIMARY KEY, 
);
CREATE PROCEDURE [dbo].[CRE_USER_PR]
	@P_NAME nvarchar(30)
    AS	
    INSERT INTO [dbo].[TBL_USER] VALUES(@P_NAME);

    CREATE PROCEDURE [dbo].[RET_USER_PR]
	@P_NAME nvarchar(30)
AS
	SELECT NAME FROM TBL_USER WHERE NAME=@P_NAME;


CREATE PROCEDURE [dbo].[RET_ALL_USER_PR]
AS
	SELECT NAME FROM TBL_USER;


CREATE PROCEDURE [dbo].[UPD_USER_PR]
	@P_NAME nvarchar(30)
AS
	UPDATE [dbo].[TBL_USER] SET NAME=@P_NAME WHERE NAME=@P_NAME;



CREATE PROCEDURE [dbo].[DEL_USER_PR]
	@P_NAME nvarchar(30)
AS
	DELETE FROM TBL_USER WHERE NAME=@P_NAME;

-------------------------------------------------------------
CREATE TABLE [dbo].[TBL_LANGUAGE](
    [NAME] NVARCHAR(30) NOT NULL PRIMARY KEY,
    [POPULARITY] INT NOT NULL
);
CREATE PROCEDURE [dbo].[CRE_LANGUAGE_PR]
	@P_NAME nvarchar(30),
    @P_POPULARITY INT
    AS	
    INSERT INTO [dbo].[TBL_LANGUAGE] VALUES(@P_NAME,@P_POPULARITY);

CREATE PROCEDURE [dbo].[RET_LANGUAGE_PR]
	@P_NAME nvarchar(30)
AS
	SELECT NAME FROM TBL_LANGUAGE WHERE NAME=@P_NAME;


CREATE PROCEDURE [dbo].[RET_ALL_LANGUAGE_PR]
AS
	SELECT NAME, POPULARITY FROM TBL_LANGUAGE;

CREATE PROCEDURE [dbo].[UPD_LANGUAGE_PR]
	@P_NAME nvarchar(30),
    @P_POPULARITY INT
AS
	UPDATE [dbo].[TBL_LANGUAGE] SET NAME=@P_NAME, POPULARITY=@P_POPULARITY WHERE NAME=@P_NAME;


CREATE PROCEDURE [dbo].[DEL_LANGUAGE_PR]
	@P_NAME nvarchar(30),
    @P_POPULARITY INT
AS
	DELETE FROM TBL_LANGUAGE WHERE NAME=@P_NAME;
-------------------------------------------------------------

CREATE TABLE [dbo].[TBL_WORD](
    [NAME] NVARCHAR(30) NOT NULL PRIMARY KEY,
    [POPULARITY] INT NOT NULL
);
CREATE PROCEDURE [dbo].[CRE_WORD_PR]
	@P_NAME nvarchar(30),
    @P_POPULARITY INT
    AS	
    INSERT INTO [dbo].[TBL_WORD] VALUES(@P_NAME,@P_POPULARITY);

CREATE PROCEDURE [dbo].[RET_WORD_PR]
	@P_NAME nvarchar(30)
AS
	SELECT NAME FROM TBL_WORD WHERE NAME=@P_NAME;


CREATE PROCEDURE [dbo].[RET_ALL_WORD_PR]
AS
	SELECT NAME, POPULARITY FROM TBL_WORD;

CREATE PROCEDURE [dbo].[UPD_WORD_PR]
	@P_NAME nvarchar(30),
    @P_POPULARITY INT
AS
	UPDATE [dbo].[TBL_WORD] SET NAME=@P_NAME, POPULARITY=@P_POPULARITY WHERE NAME=@P_NAME;


CREATE PROCEDURE [dbo].[DEL_WORD_PR]
	@P_NAME nvarchar(30),
    @P_POPULARITY INT
AS
	DELETE FROM TBL_WORD WHERE NAME=@P_NAME;
-------------------------------------------------------------
CREATE TABLE [dbo].[TBL_TRANSLATED_WORD](
    [FK_USER] NVARCHAR(30) FOREIGN KEY REFERENCES TBL_USER(NAME),
    [FK_LANGUAGE] NVARCHAR(30) FOREIGN KEY REFERENCES TBL_LANGUAGE(NAME),
    [FK_WORD] NVARCHAR(30) FOREIGN KEY REFERENCES TBL_WORD(NAME),
    [DATE] DATE NOT NULL,
    [TRANSLATE] NVARCHAR(30) NOT NULL,
    [POPULARITY] INT NOT NULL
);

CREATE PROCEDURE [dbo].[CRE_TRANSLATED_WORD_PR]
	@P_FK_USER nvarchar(30),
    @P_FK_LANGUAGE nvarchar(30),
    @P_FK_WORD nvarchar(30),
    @P_DATE DATE,
    @P_TRANSLATE nvarchar(30),
    @P_POPULARITY int
    AS	
    INSERT INTO [dbo].[TBL_TRANSLATED_WORD] VALUES(@P_FK_USER, @P_FK_LANGUAGE, @P_FK_WORD,@P_DATE, @P_TRANSLATE,@P_POPULARITY);


CREATE PROCEDURE [dbo].[RET_TRANSLATED_WORD_PR]
	@P_FK_WORD nvarchar(30)
AS
	SELECT FK_USER, FK_LANGUAGE, FK_WORD, DATE,TRANSLATE,POPULARITY FROM TBL_TRANSLATED_WORD WHERE FK_WORD=@P_FK_WORD;

CREATE PROCEDURE [dbo].[RET_ALL_TRANSLATED_WORD_PR]
AS
	SELECT FK_USER, FK_LANGUAGE, FK_WORD, DATE,TRANSLATE,POPULARITY FROM TBL_TRANSLATED_WORD;

CREATE PROCEDURE [dbo].[UPD_TRANSLATED_WORD_PR]
	@P_FK_USER nvarchar(30),
    @P_FK_LANGUAGE nvarchar(30),
    @P_FK_WORD nvarchar(30),
    @P_DATE DATE,
    @P_TRANSLATE nvarchar(30),
    @P_POPULARITY int
AS
	UPDATE [dbo].[TBL_TRANSLATED_WORD] SET FK_USER=@P_FK_USER, FK_LANGUAGE=@P_FK_LANGUAGE, FK_WORD=@P_FK_WORD, DATE=@P_DATE, TRANSLATE=@P_TRANSLATE, POPULARITY=@P_POPULARITY   WHERE FK_WORD=@P_FK_WORD;

CREATE PROCEDURE [dbo].[DEL_TRANSLATED_WORD_PR]
	@P_FK_WORD nvarchar(25)
AS
	DELETE FROM TBL_TRANSLATED_WORD WHERE FK_WORD=@P_FK_WORD;
